# predefined_lists.py

PREDEFINED_WORKS = [
    "Don Quijote de la Mancha",
    "La Odisea",
    "Hamlet",
    "Matar a un ruiseñor",
    "Cien años de soledad",
    "1984",
    "El Principito",
    "La Divina Comedia",
    "Romeo y Julieta",
    "Fahrenheit 451",
    "Moby Dick",
    "Orgullo y Prejuicio",
    "En busca del tiempo perdido",
    "Ulises",
    "El Gran Gatsby",
    "Crimen y Castigo",
    "Las Aventuras de Huckleberry Finn",
    "El Señor de los Anillos",
    "La metamorfosis",
    "Anna Karenina",
    "El retrato de Dorian Gray",
    "Las mil y una noches",
    "Guerra y Paz",
    "El extranjero",
    "Madame Bovary",
    "Las uvas de la ira",
    "El guardián entre el centeno",
    "La Iliada",
    "Beloved",
    "Jane Eyre",
    "Lolita",
    "El Proceso",
    "Los hermanos Karamazov",
    "El señor de los anillos",
    "Matar a un ruiseñor",
    "El viejo y el mar",
    "La náusea",
    "Cumbres Borrascosas",
    "El lobo estepario",
    "La isla del tesoro",
    "Rebelión en la granja",
    "El Perfume",
    "El nombre de la rosa",
    "Las ratas",
    "Los miserables",
    "El principito",
    "El código Da Vinci",
    "El perfume de la dama en negro"
]

PREDEFINED_AUTHORS = [
    "Miguel de Cervantes",
    "Homero",
    "William Shakespeare",
    "Harper Lee",
    "Gabriel García Márquez",
    "George Orwell",
    "Antoine de Saint-Exupéry",
    "Dante Alighieri",
    "William Shakespeare",
    "Ray Bradbury",
    "Herman Melville",
    "Jane Austen",
    "Marcel Proust",
    "James Joyce",
    "F. Scott Fitzgerald",
    "Fyodor Dostoevsky",
    "Mark Twain",
    "J.R.R. Tolkien",
    "Franz Kafka",
    "Leo Tolstoy",
    "Oscar Wilde",
    "Anónimo",
    "Fyodor Dostoevsky",
    "Albert Camus",
    "Gustave Flaubert",
    "John Steinbeck",
    "J.D. Salinger",
    "Homero",
    "Toni Morrison",
    "Charlotte Brontë",
    "Vladimir Nabokov",
    "Franz Kafka",
    "Fyodor Dostoevsky",
    "Harper Lee",
    "Ernest Hemingway",
    "Jean-Paul Sartre",
    "Emily Brontë",
    "Hermann Hesse",
    "Robert Louis Stevenson",
    "George Orwell",
    "Patrick Süskind",
    "Umberto Eco",
    "Herman Melville",
    "Harper Lee",
    "Antoine de Saint-Exupéry",
    "Agatha Christie",
    "Gustave Flaubert",
    "Anónimo",
    "Dan Brown",
    "Patrick Süskind"
]
